export const catchError = (e: any): void => console.error(e)
